### ISSUE TITLE
Allow limits to be optional

### ISSUE THREAD

**Issue by sstarcher** [zegl/kube-score#107]
**Describe the feature**
Ability to ignore just the limits and not the requests.  

**Expected behavior**
In our environment we want to require requests, but we leave limits optional.

**Comment by zegl** [comment]
You can disable the requirement of CPU limits with the `--ignore-container-cpu-limit` flag. See https://github.com/zegl/kube-score#configuration

Does this match your needs?

**Comment by sstarcher** [comment]
We also want to disable memory limits.

**Comment by sstarcher** [comment]
We typically set requests for cpu and memory, but not limits as if we set limits Kubernetes will set aside at least that amount of memory resulting in poor memory utilization.  We instead allow applications to float and if they use to many resources to get terminated.

**Comment by zegl** [comment]
> if they use to many resources to get terminated.

I'm curious, how are you achieving this without limits?

> but not limits as if we set limits Kubernetes will set aside at least that amount of memory resulting in poor memory utilization

Isn't it the opposite? The _request_ is reserved for the pod, and the _limit_ is what's causing the pod to be OOMKilled if the limit is reached.

**Comment by sstarcher** [comment]
If you use too many resources the kernel or the kubelet will kill you once the server near 100% memory.

```Isn't it the opposite? The request is reserved for the pod, and the limit is what's causing the pod to be OOMKilled if the limit is reached.```
This is not fully true.  If you set a limit the schedule will set aside that much memory.  If I have a service with a 1gb request and a 5gb limit and that service 99% of the time only uses 1gb the schedule will still set aside 5gb of memory for my service resulting in extremely poor utilization.  In our case we would prefer to not have the limit and allow the service to risk going OOM to improve our overall utilization.

**Comment by zegl** [comment]
> If you set a limit the schedule will set aside that much memory.

I don't think that this is true, a node is allowed to be overcommitted, i.e. the sum of limits is over the amount of resources of the node.

**Comment by sstarcher** [comment]
Yes, if overcommitment is set on your system, but it will still schedule based off of the limits if they are set.  If the limits are not set it will schedule off of the requests and those will also leverage overcommitment.  Overcommitment has no impact  on my overall assertion of our desire to be able to disable limit checks.

**Comment by zegl** [comment]
Ok, I see your point. Let's get the change as suggested in #111 merged.

**Comment by zegl** [comment]
This was fixed in #111.
