### ISSUE TITLE
Support directory as input

### ISSUE THREAD

**Issue by sstarcher** [zegl/kube-score#112]
Support for iterating through all templates in a directory.  `*.yaml` works great when you don't have subdirectories of yaml files.

**Comment by zegl** [comment]
Is this necessary? I think that it's a simpler approach to let the shell do the shell expansion?

You can run kube-score on all the testdata files like this:

```bash
kube-score score score/testdata/*.yaml
```

**Comment by sstarcher** [comment]
That works for yaml files in a directory, but does not work if you have multiple directories.  Example - https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates

**Comment by zegl** [comment]
For that you can use `find` or a shell expansion pattern like `templates/**.yaml`

```bash
kube-score score $(find . -iname '*.yaml')
```

kube-score should not do what other tools will always be better at doing.
