### ISSUE TITLE
Feature Request: verbose output should show all tests

### ISSUE THREAD

**Issue by SpreetailHurley** [zegl/kube-score#150]
During testing (e.g. new templates, new tests, etc.) I'd like to be able to pass verbose to see all of the possible tests and if / why they were skipped.

Example:
`    [OK] Deployment has host PodAntiAffinity
        * Skipped
             Skipped because the deployment has less than 2 replicas`

In specific this came up when implementing a new test that was not being applied due to the apiVersion configured in the template causing the section of the template to be skipped. A message such as:
`    [OK] New Test Here
        * Skipped
             Skipped because the apiVersion is not in: (list of matching versions)`

Another possible enhancement would be to implement a custom "skipped" status, or similar, instead of "OK"

**Comment by zegl** [comment]
This is a great suggestion! 👍 

Let me know if you would like to work on it.

**Comment by SpreetailHurley** [comment]
Hi Gustav,

I'd be happy to pick this up; I'm in the process of adding some new tests to our pipeline to extend the functionality of kube-score so this should dovetail into that work somewhere.

Thanks.

**Comment by zegl** [comment]
This is fixed as of #167. Closing.
