### ISSUE TITLE
Feature Request: Run Kube Score against deployed resources

### ISSUE THREAD

**Issue by ChrisCooney** [zegl/kube-score#184]
It would be good if Kube Score could be ran against resources that are already deployed on the cluster. This could be as simple as exporting the resource into local yaml an executing kube score against it, but this would open the door for kube score being ran regularly against an existing cluster.

**Comment by rosscdh** [comment]
+1

**Comment by dacappo** [comment]
Not sure if this is helpful, but we are currently doing the following to run kube-score against existing clusters:
```
kubectl get all -o yaml --all-namespaces | kube-score score -
```

**Comment by zegl** [comment]
This is now documented in [the README](https://github.com/zegl/kube-score#example-with-an-existing-cluster). Closing.
