### ISSUE TITLE
JSON output does not follow best practices

### ISSUE THREAD

**Issue by colindickson** [zegl/kube-score#186]
Namely, keys should be snake_case, and keys should not contain data.   

I have a PR which addresses this.

**Comment by zegl** [comment]
Hi Colin! 👋 

I'm afraid that this proposed change would be a breaking change, and might prevent users from upgrading to the next version, if they depend on the existing behaviour.

I've never been happy with the JSON output that kube-score has today, so I'm not against the proposal per se, I'm just wondering what would be the best way to roll this change out, with as few breakages as possible.

**Comment by Mattias-** [comment]
Let's make versioned scorecard json output and have a top level typemeta with kind and version!
It will still be a breaking change transitioning to that but the future will be brighter.

An additional flag could be added to define what version that should be outputted.

```
--output-format=json
--output-version=v1
```

**Comment by zegl** [comment]
> Let's make versioned scorecard json output

I'm all for it, a `--output-version` flag would fit nicely with the current set of available flags.
