### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by dbirks** [zegl/kube-score#193]
Hi! I maintain kube-score in Arch Linux's user repo, and I'm running into the new Go 1.13 [version validation](https://tip.golang.org/doc/go1.13#version-validation), but it looks like it's fixed in master. Could another release be made when you get a chance? Thanks!

**Comment by zegl** [comment]
Hey!

I'll cut v1.3.0 from 052457 and push it now. Let me know if you're still seeing version validation issues after that.

Thanks a lot for maintaining the Arch repo!

**Comment by dbirks** [comment]
Thanks! Works great :tada:
