### ISSUE TITLE
Feature: disable annotation kube-score/ignore with option

### ISSUE THREAD

**Issue by Pinpin31** [zegl/kube-score#202]
**Which version of kube-score are you using?**

> kube-score version: 1.4.0

**What did you do?**

I want to cancel deployment on Kubernetes if my clients don't respect checks requirements with kubescore.

**What did you expect to see?**

But with annotation kube-score/ignore, my clients are able to deactivate some checks that are required for deployment.

**What did you see instead?**

It would be great if an option was able to disable annotation kube-score/ignore when we do checks analytics with kubescore before deployment.

**Comment by zegl** [comment]
This is a interesting use-case, and I'd say that it goes in line with what I want kube-score to be. 👍 

If anyone wants to contribute to this feature, here are some pointers:

* [flag definition, and configuration creation](https://github.com/zegl/kube-score/blob/51d9aba2afc881022af06db7ec2a3a7d6e84617a/cmd/kube-score/main.go#L78)
* [skip ignored tests](https://github.com/zegl/kube-score/blob/3b838e9411468266c147c68e1d2de7046e53d7aa/scorecard/scorecard.go#L92-L93)
* [func that calls Add(), configuration is available here](https://github.com/zegl/kube-score/blob/51d9aba2afc881022af06db7ec2a3a7d6e84617a/score/score.go#L45)
