### ISSUE TITLE
what all parameters do i need to pass in "Docker run" command after pulling image from DockerHub

### ISSUE THREAD

**Issue by sunnygoel8** [zegl/kube-score#203]
Hi,

After pulling the image from DockerHub, what all parameters do I need to pass in "Docker run" command to keep the container running to leverage "kube-score" command ?

**Comment by zegl** [comment]
The `-helm` version of the container (`zegl/kube-score:v1.4.0-helm`) comes with bash installed. If you want to execute kube-score multiple times in the same container, you can run the following, to boot into bash in interactive mode, kube-score is on the PATH.

```
$ docker run -it --entrypoint /bin/bash zegl/kube-score:v1.4.0-helm
```

The more common use-case however, is to launch a new container every time you're running kube-score, like so: 

In this example a directory on the host is mounted into the container, to make the files available.

```bash
$ docker run -v (pwd):/project zegl/kube-score score /project/score/testdata/all-ok.yaml
networking.k8s.io/v1/NetworkPolicy foo-all-ok-netpol in testspace
    [OK] Label values
    [OK] Stable version
    [OK] NetworkPolicy targets Pod
v1/Pod pod-test-1 in testspace
    [OK] Stable version
    [OK] Label values
    [OK] Container Resources
    [OK] Container Image Tag
    [OK] Container Image Pull Policy
    [OK] Pod NetworkPolicy
    [OK] Pod Probes
    [OK] Container Security Context
```
