### ISSUE TITLE
Improve CI/CD friendliness

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#21]
It's already possible to run kube-score as a CI/CD step, and the program will exit with code 1 in case of critical errors, or on warnings if the `--exit-one-on-warning` flag is used.

* Add an example of how to use with Helm charts / helm template
* Document available flags
* Add configuration to disable some steps
* Add configuration to change the "score" a check

**Comment by tv42** [comment]
There should definitely be an output format that uses `filename:line:` prefixes to let you jump to the right place.

**Comment by zegl** [comment]
@tv42 It's a good suggestion, but as you say it's more or less impossible.

Something semi-related, that also is easy to build, is to have the export in a more condense format to better tailor to checks running on CI.

What do you think of an output format that looks something like this?

```
      ok: resourcename/namespace-abc v1/Pod
 warning: resourcename/namespace-abc v1/Service: does not target any pods
critical: resourcename/namespace-abc v1/Pod:     CPU request is not set
critical: resourcename/namespace-abc v1/Pod:     Memory request is not set
```

We could also have a flag that skips the "ok" rows, to even further reduce the output.
