### ISSUE TITLE
Distribute via krew?

### ISSUE THREAD

**Issue by corneliusweig** [zegl/kube-score#214]
:wave: Hello, maintainer of the kubectl plugin manager [krew](https://github.com/kubernetes-sigs/krew) here.

What do you think about making your plugin available via krew? You would benefit from

- Greater visibility due to krew's large user basis.
- Easier installs.
- Seamless upgrades for new plugin versions.

Krew already has around [75 plugins](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md) and more are coming in. Your static resource analyzer looks like a cool addition to the plugin index. See our [development guide](https://github.com/GoogleContainerTools/krew/blob/master/docs/DEVELOPER_GUIDE.md) if you're interested. Please also consult our [naming guide](https://github.com/kubernetes-sigs/krew/blob/master/docs/NAMING_GUIDE.md) about the plugin name. I presume that `kubectl-score` would be an acceptable plugin name.

**Comment by zegl** [comment]
Hi Cornelius!

I'm a fan of krew, so let's do it!

I've noticed that the LICENSE file is not a part of the darwin/linux tar.gz archives (#217), I'll fix that first, and then submit a PR to the krew-index. 😃 

There's also some cleanup tasks that I'd like to do, to improve usage when `kube-score` is used as a kubectl plugin, but I'll deal with that later (#215 and #216).

**Comment by corneliusweig** [comment]
Hey, very glad to hear that! There is no rush to submit to the index, so take your time. Especially #216 looks a bit weird, so I'd recommend to fix that first before adding to krew. It's important to get the UX right!

Looking forward to seeing your PR in krew-index!

**Comment by zegl** [comment]
All issues that I've raised in the comments here are now resolved, and I've submitted [a PR](https://github.com/kubernetes-sigs/krew-index/pull/517) to include score in the index!

**Comment by corneliusweig** [comment]
Looks great, thanks for contributing!
