### ISSUE TITLE
Feature request: configuration file

### ISSUE THREAD

**Issue by igoooor** [zegl/kube-score#231]
It would be great to have a configuration file we can give as an argument, where we can define which rules to include or exclude

**Comment by zegl** [comment]
Hey @igoooor,

Do you have any examples of when this would be useful?

kube-score already has the arguments `--enable-optional-test`, `--ignore-test`, `--disable-ignore-checks-annotations` and the `kube-score/ignore` annotation to control which tests that are to be executed.

**Comment by igoooor** [comment]
For example, what if I want to exclude the error "the pod does not have a matching network policy" or any other ones

**Comment by zegl** [comment]
You can do that by setting `--ignore-test pod-networkpolicy` to disable it for all objects, or by adding the annotation `kube-score/ignore: pod-networkpolicy` to a single object where you want to ignore it.

**Comment by zegl** [comment]
Since this issue has received little feedback since my last comment, I'll go ahead and close it. If you have any further comments, please leave them here, or open a new issue.

**Comment by sjuarez-asapp** [comment]
I love kube-score, we use it with GitlabCI templates, this is our use case:
- We use custom GitlabCI templates for our manifests checks
- We can use annotations to skip checks in our inhouse helm charts

But to skip some checks on oficial helm charts like the ones on `https://kubernetes-charts.storage.googleapis.com` we are forced to change our CI templates to include the `--ignore somecheck` or clone the chart locally and apply the corresponding annotations.

If we could have a `.kube-score` file to skip checks that will help to maintain our templates untouched.

Something like yamllint use: https://yamllint.readthedocs.io/en/stable/configuration.html
