### ISSUE TITLE
--ignore-container-cpu-limit does not work for container-resource-requests-equal-limits

### ISSUE THREAD

**Issue by lenhard** [zegl/kube-score#233]
First of all, thanks a lot for this excellent tool!

**Which version of kube-score are you using?**

> kube-score version: 1.5.1, commit: 097d062412883fb5a15fb273057d347ba2ee703b, built: 2020-03-01T13:00:00Z

**What did you do?**

I would like to check that a pod has equal memory requests and limits and this is included in the optional check `container-resource-requests-equal-limits`. The problem is that I only want to check for memory/requests limits, but this check also includes CPU requests/limits. I was expecting that I could turn off checks for CPU requests/limits with `--ignore-container-cpu-limit` like I can for the `container-resources` check, but it seems that this does not work.

If there is another way to just check for memory requests == memory limits, but not cpu requests == cpu limits, I am happy with using that.

**What did you expect to see?**

Expected output:
```
$ kubectl get pod some-pod -o yaml | kube-score score - --enable-optional-test container-resource-requests-equal-limits --ignore-container-cpu-limit
v1/Pod some-pod in default                                              💥
    [CRITICAL] Container Resource Requests Equal Limits
        · some-container -> Memory requests does not match limits
            Having equal requests and limits is recommended to avoid resource
            DDOS of the node during spikes. Set resources.requests.memory ==
            resources.limits.memory
```

**What did you see instead?**

Example output:
```
$ kubectl get pod some-pod -o yaml | kube-score score - --enable-optional-test container-resource-requests-equal-limits --ignore-container-cpu-limit
v1/Pod some-pod in default                                              💥
    [CRITICAL] Container Resource Requests Equal Limits
        · some-container -> CPU requests does not match limits
            Having equal requests and limits is recommended to avoid resource
            DDOS of the node during spikes. Set resources.requests.cpu ==
            resources.limits.cpu
        · some-container -> Memory requests does not match limits
            Having equal requests and limits is recommended to avoid resource
            DDOS of the node during spikes. Set resources.requests.memory ==
            resources.limits.memory
```

**Comment by zegl** [comment]
Hey @lenhard, thanks for opening this issue and opening a PR for it.

Instead of making this check more complex, and having to introduce another global command line option. What do you think of introducing two new optional checks instead? One called `Container CPI Resource Requests Equal Limits` and one called `Container Memory Resource Requests Equal Limits`.

I think that it would both simplify the code, and the ease of use, as instead of opting in for a check, and then opting-out for a part of it. You would instead only opting in for the tests that you want to have.

**Comment by lenhard** [comment]
Hi @zegl,

Thanks, that sounds reasonable. I'll see what I can do and will open a new pull request for this when I find the time. That might take a week or two, but I'll follow up on this.

**Comment by lenhard** [comment]
Hi @zegl,

I've opened a new PR with the two new optional checks. Please take a look and let me know if you like it.
