### ISSUE TITLE
review LivenessProbe/ReadinessProbe probesAreIdentical case and missing LivenessProbe

### ISSUE THREAD

**Issue by cruschke** [zegl/kube-score#248]
**Which version of kube-score are you using?**

> kube-score version: [1.6.0, commit: 1cc49a1e2003f7bff3d7bbb7e0316d69b80d1a0c, built: 2020-04-16T10:55:27Z]

**What did you do?**

run `kube-score` on deployment YAMLs that uses same LivenessProbe/ReadinessProbe probesAreIdentical case or missing LivenessProbe, wondering if criticalities are correct.

**What did you expect to see?**

There is a pretty detailed blogpost by @hjacobs on why liveness probes are dangerous 
https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html and after reading I am wondering if it makes sense to review the `kube-score` scoring for identical probes and missing liveness probe.

If I get it correct probesAreIdentical should be considered as GradeCritical, while a missing LivenessProbe I rather see as GradeAlmostOK or maybe GradeWarning. Happy to leave exact definition of criticality to you.

**Comment by hjacobs** [comment]
Thanks for the mention :smiling_face_with_three_hearts:

**Comment by zegl** [comment]
Thanks for bringing some light to this.

I agree with you that the probe configuration is hard to get right, and that it's easy to add a configuration that is doing you more harm than good.

I believe that kube-score could definitely be more useful to the users, and provide a better guide here on creating a great (or good enough) probe configuration.

I've been mapping out the current grades for some different scenarios, and have been adding the expected grades next to it.

| Has readinessProbe | Has livenessProbe | Identical probes | Current Grade | Expected Grade                                                       |
|--------------------|-------------------|------------------|---------------|----------------------------------------------------------------------|
| No                 | No                | N/A              | Critical      | Critical                                                             |
| Yes                | No                | N/A              | Warning       | Warning or AlmostOK                                                  |
| Yes                | Yes               | No               | AllOK         | AllOK                                                                |
| Yes                | Yes               | Yes              | AlmostOK      | Critical (identical probes is pretty much never what you want to do) |
| No                 | Yes               | N/A              | Critical      | Critical (no readiness)                                              |

_(The behaviour is a bit different for pods that are not targeted by a Service, but that's irrelevant for now.)_

One of the cases that you've identified, where the probes are identical, is currently a AlmostOK, and I agree with you that it should instead be a Critical error, as that's pretty much never a desired configuration.

For the case where you have a ReadinessProbe and no LivenessProbe, kube-score is currently returning a Warning as you suggested. But I'm also open for changing that to AlmostOK.

I'm also wondering if there would be a better way to explain _why_ and _when_ a probe should be used and when there's a risk of additional harm. The current comments are pretty dull and might not provide the user with the context they need to make the best decision.

**Comment by cruschke** [comment]
Thanks for looking at this subject and outlining current vs. improved behaviour. After thinking again twice I would stick to AlmostOK when livenessProbe is missing (case 2 in your table), if you would return a Warning people could be motivated to add a livenessProbe without exactly understanding the consequences (so no livenessProbe is probably better than a wrong one).

I think an easy way to clarify the _why_ and _when_ is to add the blogpost URL mentioned above into your [README_CHECKS.md](https://github.com/zegl/kube-score/blob/master/README_CHECKS.md).

**Comment by zegl** [comment]
I've now implemented the changes as suggested in [my previous comment](https://github.com/zegl/kube-score/issues/248#issuecomment-621760173), and it was merged in #249. I also created a blog-post-like [README_PROBES.md](https://github.com/zegl/kube-score/blob/master/README_PROBES.md) that goes a bit more in-depth about why the new recommendations are they way they are.

I hope that you can take a look at the changes, to make sure that it works as expected. 😃

**Comment by cruschke** [comment]
LGTM!

Tested release build vs. build from master using my "suspicious" YAMLs where readiness probe is identical to liveness probe:

```
...
         livenessProbe:
            httpGet:
              path: /manifest.json
              port: 80
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 80
...
```

* kube-score version: 1.6.0, commit: 1cc49a1e2003f7bff3d7bbb7e0316d69b80d1a0c, built: 2020-04-16T10:55:27Z

`[OK] Pod Probes
    · Pod has the same readiness and liveness probe
        It's recommended to have different probes for the two different
        purposes.`

* build from master

`[CRITICAL] Pod Probes
    · Container has the same readiness and liveness probe
        Using the same probe for liveness and readiness is very likely
        dangerous. Generally it's better to avoid the livenessProbe than
        re-using the readinessProbe.
        More information: https://github.com/zegl/kube-score/blob/master/README_PROBES.md`

The README_PROBES.md is a pretty good summary.

Thanks for addressing this subject.

**Comment by zegl** [comment]
Thanks for confirming that things are looking great! I really appreciate it! 🥇 

I'll close this issue now, and start to prepare for a new release of kube-score.
