### ISSUE TITLE
Docker: helm floating tag

### ISSUE THREAD

**Issue by antechrestos** [zegl/kube-score#268]
Hello

We are trying to use a latest like version of your docker image in gitlab ci pipeline. As gitlab needs a shell image, we use the `-helm` images since the normal one are scratch image.

Would it be possible to publish a floating `helm` image in order to always get the latest image for pipelines?

Kaniko also provides two floating tag (latest for `scratch` and `debug` for ci/shell purpose) and each version has two version (`scratch` and one with shell)

Besides I did not find the `Dockerfile` in your repository..

Thank you very much

**Comment by zegl** [comment]
Hey,

This makes sense, when doing implementing this I also discovered that `zegl/kube-score:latest` doesn't point to the latest version (currently v1.7.1), so thanks for highlighting this.

The sources to the Dockerfiles are [here](https://github.com/zegl/kube-score/blob/master/cmd/kube-score/Dockerfile) and [here](https://github.com/zegl/kube-score/blob/master/cmd/kube-score/helm.Dockerfile).

I'll push a fix and create a new release in a few minutes.

**Comment by antechrestos** [comment]
@zegl Greate!

Thank you very much

**Comment by zegl** [comment]
New images for [:latest](https://hub.docker.com/layers/zegl/kube-score/latest/images/sha256-333fa94c0b6da5a073056111e01dc72fafd2fcf616a7dd073b027b6bea0fe84c?context=repo) and [:latest-helm](https://hub.docker.com/layers/zegl/kube-score/latest-helm/images/sha256-511927e98452f8f4d2945fd02b86ec0c96e3f6d3199b1dcf91488511ff045f4e?context=repo) are now out!
