### ISSUE TITLE
Docker image with kustomize

### ISSUE THREAD

**Issue by lcostea** [zegl/kube-score#273]
There are many applications that use kustomize for manifests, like [argo-cd](https://github.com/argoproj/argo-cd/tree/master/manifests), [flagger](https://github.com/weaveworks/flagger/tree/master/kustomize) or [istio](https://github.com/istio/istio/tree/master/manifests/charts). It would be great if we could have a docker image containing kustomize, so developers will not need to build their own.

If needed I can provide a PR.

**Comment by zegl** [comment]
@lcostea This makes sense to me, if you want to, please send a PR.

For reference, the helm Dockerfile can be found [here](https://github.com/zegl/kube-score/blob/master/cmd/kube-score/helm.Dockerfile), and is referenced [here](https://github.com/zegl/kube-score/blob/master/.goreleaser.yml#L35-L42) in the release tooling. Please use a similar setup with the same versions of Alpine, and use a similar structure for verifying the checksum of all downloads. Thanks!

**Comment by lcostea** [comment]
Great, working on it
