### ISSUE TITLE
Validate serviceName of a StatefulSet

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#315]
> serviceName is the name of the service that governs this StatefulSet. This service must exist before the StatefulSet, and is responsible for the network identity of the set. Pods get DNS/hostnames that follow the pattern: pod-specific-string.serviceName.default.svc.cluster.local where "pod-specific-string" is managed by the StatefulSet controller.

[From the documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#statefulsetspec-v1-apps).

kube-score should check that a StatefulSets `.spec.serviceName` matches a Service in the same namespace.

**Comment by neglect-yp** [comment]
@zegl Hello, may I work on this issue? If it's OK, I'll create a PR from tomorrow for Hacktoberfest.

**Comment by zegl** [comment]
Hey @neglect-yp, yes, please do. I'll assign this issue to you. Have fun!
