### ISSUE TITLE
Split "Container Security Context"

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#325]
As shown in #204, there's a need to being able to disable the UID and GID checks of the ["Container Security Context"](https://github.com/zegl/kube-score/blob/d9be66a97141a270ba0bb44e87347ce1dfd96256/score/security/security.go#L17) check without disabling the other checks that are made. I'm therefore proposing to split this check into three separate ones:

* Container Security Context User/Group ID
* Container Security Context Privileged
* Container Security Context ReadOnlyRootFilesystem

Keeping all 3+1 versions around would not be desirable, and I'm proposing to use a three setup rollout plan:

* v1.n: Add the three new checks, using opt-in, and deprecate the existing "Container Security Context" check.
* v1.n+1: Enable the three new checks by default, mark "Container Security Context" as optional/opt-in.
* v1.n+2: Remove "Container Security Context".

**Comment by markuslackner** [comment]
Hi! I would start implementing this feature, if there is not someone else who has already started with implemting.

**Comment by zegl** [comment]
@markuslackner I don't know of anyone else that has started to implement this, so feel free to go ahead! 👍
