### ISSUE TITLE
 💥

### ISSUE THREAD

**Issue by nevetS** [zegl/kube-score#331]
**Which version of kube-score are you using?**

> kube-score version: [e.g. 0.3.0]

**What did you do?**

I ran kubescore

**What did you expect to see?**

Not something that makes my monitor look like it's broken

> A clear and concise description of what you expected to happen.

apps/v1/StatefulSet mytestfile in cds-dev                               💥
 

> A description of what happened, include logs and program output

The bullet point on the far right doesn't serve its purpose IMO.  It's red here on github, but in my terminal it's light blue and looks more like a scratch in my monitor than a bullet point.  I spent more time wondering what happened to my screen than worrying about the warnings.

Then I had a good laugh.  You got me.

**Comment by zegl** [comment]
Hey, 

I'm guessing that you're using a terminal with less-than-perfect unicode support (this character was added to Unicode 10 years ago). kube-score has other output formats such as `--output ci` that uses ASCII only output, which might work better for you.

I unfortunately don't think that there is anything that kube-score can do about this, so I'm going to close the issue for now.
