### ISSUE TITLE
Helm V3 Support

### ISSUE THREAD

**Issue by doughoke** [zegl/kube-score#345]
**Which version of kube-score are you using?**

> kube-score version: 1.10.0

**What did you do?**

> Attempting to helm template per spec on Readme in an automated pipeline that can run your docker image against a helm/values pairing for notification of best practices prior to helm install or kubectl apply <helm template>.

**What did you expect to see?**
It work on a helmV3 chart when I run template.  One or two helm template switches in V2 helm cli are different or removed.

> The ability to run helm template however most charts have flipped to v3 and therefore incompatibility issues could arise.
**What did you see instead?**

> A description of what happened, include logs and program output
No logs just a request...

Should I do a pull request and update your helm.Dockerfile or create a new one helmv3.Docerfile.  Impact would be that existing users could be impacted on just updating original.  Second option will most likely cause you to have another docker build/tag line. Either way, you may want to deprecate helm v2 support at some point.

I have a fork already just let me know which direction you would like. I can get the dockerfile done rather quickly as it is just find/replace.

**Comment by zegl** [comment]
Hey @doughoke,

Thanks for taking your time to think about this. While I agree that support for Helm 2 likely should be deprecated at _some point_, I don't think that that time is now (I don't have any data to back this claim, it's just my gut feeling). Adding a new `helm3.Dockefile` sounds like a great way to get this started, without having to worry about creating any breaking changes.

**Comment by doughoke** [comment]
Thanks for the follow up. Pull request submitted
[https://github.com/zegl/kube-score/pull/346](url)

**Comment by doughoke** [comment]
Closing with merge of above PR ^^^
