### ISSUE TITLE
Kubescore should allow using matchExpressions in podSelector

### ISSUE THREAD

**Issue by wargamez** [zegl/kube-score#359]
**Which version of kube-score are you using?**

> kube-score version:
1.10.1

**What did you do?**
Due to a bug when using commonLabels in kustomize (https://github.com/kubernetes-sigs/kustomize/issues/2034) the only workaround I know of is to use MatchExpressions instead. However, kubescore seems to require the usage of matchLabels only. 
e.g
egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: example.com/name
                operator: In
                values:
                  - memcached

**What did you expect to see?**
I expected kubescore to not mark this as an CRITICAL error, and I would like to avoid using 
annotations:
    kube-score/ignore: networkpolicy-targets-pod

**Comment by zegl** [comment]
kube-score generally does support matchExpressions. Could you please share a complete example that reproduces this bug? With both the NetworkPolicy and the Pod/Deployment/etc that you're using.

Thanks.
