### ISSUE TITLE
Container image pull policy is asking for an invalid value

### ISSUE THREAD

**Issue by rvillane** [zegl/kube-score#39]
My YAML container image pull policy says:
 imagePullPolicy: Always

and kube-core is recommending "PullAlways" value
[CRITICAL] Container Image Pull Policy
        * esp -> ImagePullPolicy is not set to PullAlways
             It's recommended to always set the ImagePullPolicy to PullAlways, to make sure that the imagePullSecrets are always correct, and to always get the image you want.

however, that is not a valid value according to latest API definition:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/

Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images

**Comment by zegl** [comment]
Hey @rvillane!

There is a bug in the comment that recommends `"PullAlways"` as the value, but the condition should already have been looking for the value `"Always"`.

I'll also add logic that checks if the tag is `:latest` or missing, and mute this warning in that situation. Note tough, that the `"Container Image Tag"` test will issue a critical warning if the tag is missing or set to ":latest".

Thanks for the bug report!
