### ISSUE TITLE
readiness and liveness checks should not be identical

### ISSUE THREAD

**Issue by Zhann** [zegl/kube-score#41]
First off: thanks for this tool! Gonna use it in our CI. 😃 ❤️ 

My question: what are the recommendations based on? Is there a guide to best practices somewhere?

More specifically:

> "Container probes, both readiness and liveness checks should be configured, and should not be identical". 

I fail to see the harm in having identical readiness/liveness checks? It's done in the official documentation as well: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-tcp-liveness-probe

In our case this is a HTTP health check. You could even argue they are not identical, both `initialDelaySeconds` and `timeoutSeconds` are different.

**Comment by zegl** [comment]
@Zhann Hey, I'm glad that you're enjoying my tool!

The default recommendations are mostly based on my own experience of running applications on Kubernetes. I of course welcome recommendations from others, and would like to see what you think about it.

This check comes from the fact that Kubernetes uses the two different probe types for two completely different purposes.

For example: If you have an application that depends on a database, it is a good idea to check DB connectivity in the `readinessProbe`, but not in the `livenessProbe`. You don't want your pod to be killed if the db is down, but you do want to unregister from Services. This especially true if your application takes a long time too start up.

That's my motivation for it. Do you agree with it?

Internally kube-score has a ranking system between 0 and 10, where 10 is the best. Having probes, but identical ones (except for the different delay and timeouts), [is a score 7/10](https://github.com/zegl/kube-score/blob/2f21dd29b5d3538e5b1d8e8258da4ff535639664/score/probes/probes.go#L85). I've been planning to expose these "grades", and making the warning and critical levels adjustable. To solve citations like this one. All other "warnings" are currently a 5/10.
