### ISSUE TITLE
Enable more linters

### ISSUE THREAD

**Issue by zegl** [zegl/kube-score#440]
kube-score is linted with golangci-lint, but some of the linters [have been disabled](https://github.com/zegl/kube-score/blob/master/.golangci.yml).

1. Update `.golangci.yml` to enable more linters
2. Run `golangci-lint run` to find the issues that the new linters find.
3. Fix the issues until none are left.
4. Send a PR! 😍

**Comment by atombrella** [comment]
@zegl Could you close this issue, please?

**Comment by zegl** [comment]
@atombrella Yes! Thanks for working on this :-)
