### ISSUE TITLE
Feature request: Support JUnit XML output format

### ISSUE THREAD

**Issue by atombrella** [zegl/kube-score#459]
I've experimented a bit with this tool on some YAML files at work. The output format is currently limited to `human` (which is neat for just finding and fixing potential issues) and `ci` (just one line per test). It'd be nice to support also [junit](https://llg.cubic.org/docs/junit/). This format allows to see the results more clearly for each of the tests. JUnit is supported also by GitLab, and on other platforms (GitHub), and despite the misleading name, it appears to be a more universal format.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml
https://docs.gitlab.com/ee/ci/unit_test_reports.html
https://support.atlassian.com/bitbucket-cloud/docs/test-reporting-in-pipelines/

**Comment by atombrella** [comment]
I can give it a go, but will probably reach out for assistance once I have something ready for a PR.

**Comment by kmarteaux** [comment]
There is a tool already available one could leverage -- https://github.com/jstemmer/go-junit-report. I did the following in my local env -- 

$ go get github.com/jstemmer/go-junit-report
$ go build github.com/jstemmer/go-junit-report

$ go test -v $(pwd)/cmd/kube-score | go-junit-report
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
        <testsuite tests="2" failures="0" time="0.000" name="github.com/zegl/kube-score/cmd/kube-score">        
                <properties>
                        <property name="go.version" value="go1.18.1"></property>
                </properties>
                <testcase classname="kube-score" name="TestParseCli" time="0.000"></testcase>
                <testcase classname="kube-score" name="TestExecName" time="0.000"></testcase>
        </testsuite>
</testsuites>

**Comment by kaluzaaa** [comment]
@zegl can you assign this issues to me? I will try to upload a pr within the next week.

**Comment by baracoder** [comment]
@kaluzaaa any progress on the PR. I think this is a useful feature to integrate with gitlab CI

**Comment by wscourge** [comment]
@zegl please lmk if this is up for grabs, or if not what's the timeline

**Comment by zegl** [comment]
@wscourge I don't think that anyone is working on this at the moment. Feel free to work on it, and send a PR. :-)

**Comment by sebhoss** [comment]
I've opened https://github.com/zegl/kube-score/pull/603 to add native JUnit output support - please take a look everyone :heart:

**Comment by gruzchik** [comment]
@sebhoss thank you for this important update! Could you keep us inform in this thread when this feature will be implemented

@zegl @sebhoss thanks in advance!

**Comment by zegl** [comment]
@gruzchik This feature has been merged now!

**Comment by gruzchik** [comment]
Thank you very much @zegl ! There are awesome news, could you please keep us inform when we have a chance to see this update in the next release, I use a release pulling of versions and comparing of this with the release checksum
