### ISSUE TITLE
Flag to disable checking network policy.

### ISSUE THREAD

**Issue by azalio** [zegl/kube-score#46]
Hello!
I use calico network policy definition (https://docs.projectcalico.org/v3.2/reference/calicoctl/resources/networkpolicy).
And until somebody adds support for calico, unfortunately, I can't use kube-score in my CI/CD.

**Comment by zegl** [comment]
Hey @azalio!

I agree with you, we need to have some sort of flag/config that can be used to disable or enable single tests. I'll make a fix for this soon!

**Comment by pesimon** [comment]
With https://github.com/zegl/kube-score/pull/51 can be disabled with 
`kube-score --ignore-test pod-networkpolicy`

**Comment by zegl** [comment]
This feature is now available on the master branch. I'll make a release with this feature included soon.
