### ISSUE TITLE
Container Image Pull Policy - Always vs. IfNotPresent

### ISSUE THREAD

**Issue by pesimon** [zegl/kube-score#48]
First, thanks for starting this project. It's really neat. 
 
It would be nice to to have certain test configurable - e.g. Container Image Pull Policy 

Looking at the [helm charts](https://github.com/helm/charts/) the majority is using  `IfNotPresent` as it's default.  
```
find . -name values.yaml -print0 | xargs -0  git grep "imagePullPolicy:" | grep IfNotPresent | wc -l                                               
      54
find . -name values.yaml -print0 | xargs -0  git grep "imagePullPolicy:" | grep Always | wc -l                                                
       4
```
Personally I would argue, that `Always` needs to be set when `:latest` or some other static tag is specified.  `IfNotPresent` is advantageous as it reduces pod restart times and does not introduce a a hard dependency to the docker registry when restarting pods.

**Comment by zegl** [comment]
@pesimon Hey, I'm glad that you like it.

I've been working on a feature to disable tests that you don't need. It will be available in the next release. :)

**Comment by pesimon** [comment]
Great, will close this one. Please make sure to update the Docker image on https://hub.docker.com/r/zegl/kube-score/tags/ as well ;-)

**Comment by zegl** [comment]
@dawidmalina You are correct that images are immutable, and will not change, but that's not the issue. The issue with `IfNotPresent` is that you _can_ run images that you should not have access to if you're using `imagePullSecrets`.

If you have two deployments, in two different namespaces, that have their own `imagePullSecrets` that grants access to one image each. Pods in deployment A should only have access to image A, and deployment B should only have access to image B.

When `imagePullPolicy` is set to `Always`, the `imagePullSecret` access check is skipped if the image already exists on the node. This means that pods in deployment A gets access to image B, if the pod is scheduled on a node that already has the image.

Docker and other container runtimes are smart enough to not re-download the entire image if hasn't changed. The registry will answer with the corresponding hash of the tag, and the daemon will not download anything if it has changed.

The only drawback of `Always` is that pods will not be able to start if the node is not able to communicate with the registry.

**Comment by dawidmalina** [comment]
I understand your point however is more topic how much do you trust your workload and what kind of policy you have according cluster isolation. But we could continue this discussion more and more - it's not the point ;)

I know that I can disable this check with `--ignore-test container-image-pull-policy` but it would be (at lest for me and probably for @pesimon as well) desirable if we could have ability to configure this. Maybe some kind of option to switch from default `Always` policy to `IfNotPresent`. What do you think @zegl ?

**Comment by dawidmalina** [comment]
Maybe we could correlate it with `ImagePullSecrets`? If pod is configured with `ImagePullSecrets` then `imagePullPolicy` must be set to `Always`. If not then we coud failback to kubernetes default `IfNotPresent`.
