### ISSUE TITLE
feature request: topologySpreadConstraints

### ISSUE THREAD

**Issue by errm** [zegl/kube-score#495]
We are using topologySpreadConstraints on our deployments

I have disabled the deployment-has-host-podantiaffinity check as a result, but it would be great if an appropriate topologySpreadConstraints would also satisfy this check!

**Comment by kmarteaux** [comment]
@zegl - Do you want me to add Pod.spec.topologySpreadConstraint checks to the apps package? If so, I will do it.

**Comment by zegl** [comment]
@kmarteaux Please do! This sounds like a great feature. I'll assign you. :-)
