### ISSUE TITLE
Please submit a PR to update version in krew-index

### ISSUE THREAD

**Issue by gabrimonfa** [zegl/kube-score#500]
**Which version of kube-score are you using?**
1.10, iinstalled through krew

**What did you do?**
I want to update to latest 1.14

**What did you expect to see?**
The plugin is updated to latest 1.14 version

**What did you see instead?**
The plugin is already at latest version

**A complete description of the steps you took to trigger the incorrect behaviour.**
I try to update through krew but in krew index most updated version is 1.10.
I try to open a ticket in krew index (https://github.com/kubernetes-sigs/krew-index/issues/2768)  -  I mean, it's the same official repository, all it took is to update a 0 with a 4 in score.yaml file.
It was promptly closed asking me to talk with plugin owner.
So, sorry for bothering, can you please submit a PR to update the version in krew-index?

**Comment by zegl** [comment]
Done! https://github.com/kubernetes-sigs/krew-index/pull/2769
