### ISSUE TITLE
Minor improvements on the CI

### ISSUE THREAD

**Issue by lleontop** [zegl/kube-score#54]
Hi! Thank you for your great tool!

I would like to propose some minor improvements on the building/CI.
Firstly it would be great to have a Dockerfile that builds and runs the kube-scope in a multi layer docker build so as to be easier for someone to download and use the tool without having to setup GO in his/her env (or easily test some changes when changing code).

Secondly based on the above you could have circle CI pushing the latest code under a latest tag on DockerHub so someone doesn't even has to build anything, just gets the docker image and starts using the latest code of the tool.

I have done both of the above in the past so I would be more than happy to contribute if you think these proposals could be useful.

**Comment by zegl** [comment]
@lleontop Hey, thanks for reaching out.

I have added (in #58 and #61) a step to the CI that automatically pushes a new `:latest` after every merge to master. I'd like to hear your feedback on it. :)

**Comment by lleontop** [comment]
Hi @zegl ! It looks great! Now I can officially use your latest fixes without waiting for a release :). 

I was just wondering though why did you choose the multiple ADD commands for each folder instead of a single ADD/COPY in the first stage? In a test that I did `COPY . .` was also working also fine unless I am missing something! 

Thanks again for the great tool and fast support!
