### ISSUE TITLE
Add check for replicas > 1

### ISSUE THREAD

**Issue by joshiste** [zegl/kube-score#569]
There is no check for the configured number of replicas. 

From a resilience perspective, it would be reasonable to add a warning for statefulsets/deployments targeted by a service, and have the replica unset or = 1 and not have a horizontal pod autoscaler.
For the same reason, if they have a horizontal pod auto scaler, it should be checked for minReplicas = 1.

KubeLinter has both of these checks. Let me know what you think. If you find this acceptable, I'd happily contribute a PR.

**Comment by zegl** [comment]
I think that this makes sense.

We should have a warning for: Deployments, that _are not_ targeted by a HorizontalPodAutoscaler, that _are_ targeted by Services, where replicas is unset or explicitly set to 1.

I don't think that the same can be said for StatefulSets. StatefulSets are usually trickier to scale, and the warning would in many cases not be actionable. Which would just lead to the warning being ignored.

PRs are very welcome :)
