### ISSUE TITLE
Add check for update strategy

### ISSUE THREAD

**Issue by joshiste** [zegl/kube-score#570]
There is no check on the update strategy.

To avoid interruptions during updates of deployments/statefulsets it's advisable to use a rolling update strategy. 
I think it is reasonable to add this check if the pods are targeted by a service to check for the update strategy.

KubeLinter has this check. Let me know what you think. If you find this acceptable, I'd happily contribute a PR.

**Comment by zegl** [comment]
Yes, this makes sense for Deployments. Add a warning if the strategy is "Recreate" and the Deployment is targeted by a Service.
