### ISSUE TITLE
Please fix optional check for seccomp

### ISSUE THREAD

**Issue by wargamez** [zegl/kube-score#590]
It seems the optional check for seccomp only looks at some annotation (Which I am not sure is the right way to look for this). Kubernetes documentations says this should be set in securityContext or podSecurityContext and seems kubeaudit thinks the same. So even if I have this set like that (Without annotation, but in Context) kubescore is giving a warning. 
Ref: https://github.com/Shopify/kubeaudit/blob/main/docs/auditors/seccomp.md and https://kubernetes.io/docs/tutorials/security/seccomp/

Also applying dry-run label on migration from psp to restricted psa  the warining on not set vanishes when set as part of any securityContext...

/E

**Comment by kmarteaux** [comment]
@zegl - I will update the seccomp check to behave as @wargamez describes.  I recently got tripped up on the same behavior.

**Comment by zegl** [comment]
@kmarteaux Thanks! 🙏
