### ISSUE TITLE
Issue with a using README_CHECKS.md rules for exlude some rule

### ISSUE THREAD

**Issue by gruzchik** [zegl/kube-score#616]
**Which version of kube-score are you using?**

> kube-score version: v1.18.0

**What did you do?**

>run kube-score with excluding of some tests using`--ignore-test` from https://github.com/zegl/kube-score/blob/master/README_CHECKS.md

**What did you expect to see?**

> when we run option `--ignore-test`  we need to have ability to exclude an of default rules

**What did you see instead?**

> When I try run exclude test from the [next commit](https://github.com/zegl/kube-score/commit/810be6515e6a0bebb158f8f8b512cd0b4f672918#diff-a2519e50a56a64b96f5afce8fae0982a7d3b065dc5d5132e4c132d6824e30dccR8)  I do not have this in the checklist https://github.com/zegl/kube-score/blob/master/README_CHECKS.md

**Comment by zegl** [comment]
Fixed in #617
