### ISSUE TITLE
Let a specific version of Kubernetes be specified when kube-scoring a file

### ISSUE THREAD

**Issue by jameshiew** [zegl/kube-score#63]
e.g. a warning like the below is emitted when kube-scoring a Deployment file
```
    [WARNING] Stable version
        * The apiVersion and kind extensions/v1beta1/Deployment is deprecated
             It's recommended to use apps/v1 instead
```
Deprecation information is Kubernetes version-specific I'm guessing, so this warning should depend on the version of Kubernetes being used.

**Comment by mrgleeco** [comment]
renewed interest! 
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
