### ISSUE TITLE
check for nodeport usage in service is missing

### ISSUE THREAD

**Issue by monotek** [zegl/kube-score#64]
**Describe the bug**
We'd like to prevent usage of nodeport in our services. Currently there is no check for this.

Reason: https://oteemo.com/2017/12/12/think-nodeport-kubernetes/

**To Reproduce**

```
Insert a YAML document that triggers the incorrect behaviour
```

**Expected behavior**

**Version**
kube-score version: [e.g. 0.3.0]

**Additional context**

**Comment by zegl** [comment]
@monotek Nice suggestion, I'll make sure to add it.

kube-score might not be the best solution to _prevent_ use of NodePorts tough, [Kubernetes ResourceQuotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) are a better and more fool-proof solution. Set `service.nodeports` to 0, to effectively prevent creation of nodeport services.

**Comment by monotek** [comment]
Yes, i meaned we like to be warned if somebody trys to use it :-)

**Comment by tammersaleh** [comment]
I'm trying to find documentation that shows that `NodePort` services aren't compatible with `NetworkPolicies`, but coming up empty (other than that article that is linked in this issue).  Is there a better description of the underlying problem somewhere?
